### ISSUE TITLE
Wrong parameter inside call to training function

### ISSUE THREAD

**Issue by shles** [satojkovic/DeepLogo#35]
There is a mistake in calling to trainig function:
```$ python ${OBJECT_DETECTION_API_DIR}/legacy/train.py --logtostderr --pipeline_config_path=ssd_inception_v2.config --train_dir=training```
If I understand correctly, should be: 
```$ python ${OBJECT_DETECTION_API_DIR}/legacy/train.py --logtostderr --pipeline_config_path=ssd_inception_v2_coco.config --train_dir=training```
The **coco** postfix is missing

**Comment by satojkovic** [comment]
Thanks. Fixed!
